name = "etch-cms"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["* * * * *"]

[site]
bucket = "./client/dist"

[[d1_databases]]
binding = "DB"
database_name = "etch-cms-db"
database_id = "134c3d7d-0578-4184-a71c-0d7259e61e09"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "etch-cms-assets"

[vars]
ENVIRONMENT = "production"
